connector:
  data-access:
    # Select the data access object implementation for your target platform
    # Uncomment the following line to access Moodle
    implementation: MoodleConnectorDaoImpl
    # Uncomment the following line to access Stud.IP
    #implementation: StudipConnectorDaoImpl
    # Uncomment the following line to get a dummy implementation
    #implementation: DummyConnectorDaoImpl
    jdbc:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/moodle?zeroDateTimeBehavior=convertToNull
      username: arsnova
      password: arsnova

  authentication:
    username: arsnova
    password: arsnova
